version: "3.8"

services:
    xstro-app:
        build:
            context: . # Use the current directory (where Dockerfile is located)
            dockerfile: Dockerfile # Name of the Dockerfile (default name assumed here)
        image: xstro-app:latest # Optional: tags the built image
        container_name: xstro-container # Optional: names the running container
        working_dir: /root/xstro # Sets the working directory inside the container
        command: ["npm", "start"] # Command to run the app
        volumes: # Optional: persists data or mounts local files
            - ./:/root/xstro # Maps current directory to /root/xstro in the container
        environment: # Optional: sets environment variables if needed
            - NODE_ENV=production
        restart: unless-stopped # Optional: restarts container unless manually stopped
