services:
  - type: web
    name: Xstro
    runtime: docker
    repo: https://github.com/AstroX11/Xstro
    plan: free
    envVars:
      - key: SESSION
        sync: false
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
version: '1'
