name: Docker Build

on:
  push:
    branches: [ "core" ]
  pull_request:
    branches: [ "core" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag xstro:$(date +%s)
