name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: >
          👋 Welcome and thanks for opening your first issue!  
          We appreciate your contribution and look forward to collaborating with you.  
          Please make sure you’ve provided all the necessary details to help us review your issue efficiently.  
          If you have any questions, check our contributing guide or feel free to ask.

          🚀 Happy contributing!
        pr-message: >
          🎉 Welcome and thanks for submitting your first pull request!  
          We appreciate your effort and contribution to improving this project.  
          Our team will review your PR as soon as possible.  
          In the meantime, double-check that your changes align with our contributing guidelines.

          💬 If you have any additional context to share, feel free to comment in your PR.  
          Thank you again and happy coding!
