name: Personalized Greetings

on: 
  pull_request_target:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Greet PR authors
        uses: peter-evans/comment-pr@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            👋 Hello @${{ github.actor }}! Thank you for submitting a pull request!
            We appreciate your time and effort. Your contribution is important to us!
            If you need any help or have questions, feel free to reach out. Let's collaborate and improve this project together!

      - name: Clone the forked repository using Git
        run: |
          AUTHOR=${{ github.actor }}
          git clone https://github.com/${AUTHOR}/Xstro.git
