name: Labeler

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml  # Path to the labeler config
        sync-labels: false  # Don't remove labels not defined in the config
        dot: true  # Include files/folders that begin with a dot
