name: Lint

on:
  push:
    branches: [stable]
  pull_request:
    branches: [stable]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Install Yarn globally
        run: npm install -g yarn

      - name: Allow TypeScript errors during Baileys install
        run: echo 'TSC_COMPILE_ON_ERROR=true' >> $GITHUB_ENV

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm eslint . --ext .ts,.tsx,.js
